# Generated by Django 3.0.5 on 2020-04-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(related_name='_profile_friends_+', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='notif_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
