# Generated by Django 3.0.5 on 2020-05-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200429_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
