# Generated by Django 3.0.5 on 2020-05-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200502_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupf',
            name='group_name',
            field=models.CharField(choices=[('TECAPP', 'Tech: App development'), ('TECCP', 'Tech: Competitive Programming'), ('TECAI', 'Tech: Artificial Intelligence'), ('TECDS', 'Tech: Data Science'), ('CPEUPSC', 'Competitive exams: UPSC'), ('CPECAT', 'Competitive exams: CAT'), ('CPEGRE', 'Competitive exams: GRE'), ('SPFGYM', 'Sports and Fitness: Gym'), ('SPFFB', 'Sports and Fitness: Football'), ('SPFCRI', 'Sports and Fitness: Cricket'), ('ARTSKE', 'Arts and Crafts: Sketching'), ('ARTPAC', 'Arts and Crafts: Paper Craft'), ('ARTDA', 'Arts and Crafts: Digital Arts'), ('MAMMI', 'Music and Movies: Musical Instruments'), ('MAMFM', 'Music and Movies: Film making')], max_length=100),
        ),
    ]
