# Generated by Django 3.0.5 on 2020-05-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_signup_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupf',
            name='group_name',
            field=models.CharField(max_length=100),
        ),
    ]
