# Generated by Django 3.0.5 on 2020-05-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200503_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='group_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='groupf',
            name='group_name',
            field=models.CharField(choices=[('', '---------'), ('TECAPP', 'Tech: App development'), ('TECCP', 'Tech: Competitive Programming'), ('TECAI', 'Tech: Artificial Intelligence'), ('TECDS', 'Tech: Data Science'), ('CPEUPSC', 'Competitive exams: UPSC'), ('CPECAT', 'Competitive exams: CAT'), ('CPEGRE', 'Competitive exams: GRE'), ('CPEGATE', 'Competitive exams: GATE'), ('SPFGYM', 'Sports and Fitness: Gym'), ('SPFFB', 'Sports and Fitness: Football'), ('SPFCRI', 'Sports and Fitness: Cricket'), ('ARTSKE', 'Arts and Crafts: Sketching'), ('ARTPAC', 'Arts and Crafts: Paper Craft'), ('ARTDA', 'Arts and Crafts: Digital Arts'), ('MAMMI', 'Music and Movies: Musical Instruments'), ('MAMFM', 'Music and Movies: Film making')], max_length=100),
        ),
    ]
